### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rubiin** [dziraf/admin-bro-mikroorm#1]
gives me error at Resource.?

**Comment by dziraf** [comment]
Can you be more specific? What exact error you're getting and could you show your adminbro config?

**Comment by rubiin** [comment]
https://i.imgur.com/aY42vlu.png while using the module i get this error

**Comment by dziraf** [comment]
What's your Node version? I tested this only using Node.js v14 but if it's an issue I can try to build it to an older ES version. Could you try to run it with Node v14+ (if yours is lower) to see if it works then?

**Comment by rubiin** [comment]
i am using node 12.21.0, let me try with 14 and see if it works
