### ISSUE TITLE
Question: Optimize

### ISSUE THREAD

**Issue by rubiin** [dziraf/admin-bro-mikroorm#3]
How can we remove the Resource.SetOrm()

**Comment by dziraf** [comment]
I don't think there's a way to do that. Entity manager is only exposed through mikro orm instance

**Comment by rubiin** [comment]
typeorm does something like this https://github.com/SoftwareBrothers/admin-bro-typeorm/blob/master/src/Database.ts and mongoose manages with this https://github.com/SoftwareBrothers/admin-bro-mongoose/blob/master/src/database.ts

**Comment by dziraf** [comment]
Yes but they support Active Record approach which MikroORM doesn't
